language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.phpunit
        - $HOME/.splitsh

env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
    fast_finish: true
    include:
          # Lowest stable packages and latest PHP version
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak" PUBLISH=1

          # Latest stable packages
        - php: 7.1
          env: PHP_CS=true
        - php: 7.2
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

          # Symfony LTS versions
        - php: 7.2
          env: DEPENDENCIES="symfony/lts:^3"

          # Latest unstable packages
        - php: 7.2
          env: STABILITY="dev"

    allow_failures:
        - env: STABILITY="dev"

before_install:
    - echo -e "machine github.com\n  login $GITHUB_API_TOKEN" >> ~/.netrc
    - if [[ $PUBLISH && $TRAVIS_PULL_REQUEST = false ]]; then ./publish; fi
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi
    - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi
    - if [[ $PHP_CS = true ]]; then composer require --no-update friendsofphp/php-cs-fixer; fi

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./phpunit install

script:
    - ./phpunit $PHPUNIT_FLAGS
    - if [[ $PHP_CS = true ]]; then vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no; fi
