language: php

git:
    depth: false

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/vendor/bin/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"

before_install:
    - phpenv config-rm xdebug.ini

install:
    - composer update --prefer-dist --no-interaction
    - bin/phpunit install

script:
    - bin/phpunit

jobs:
    include:
        # Split test
        -
            php: 7.1
            script:
                - bin/splittest

        # Symfony LTS 3 requirement test, code style test, code coverage report
        -
            php: 7.2
            before_install:
                - composer require --no-update symfony/lts:^3
                - composer require --no-update friendsofphp/php-cs-fixer
            script:
                - vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
                - phpenv config-add xdebug.ini
                - bin/phpunit -v --coverage-clover=coverage.xml
            after_success:
                - bash <(curl -s https://codecov.io/bash)

        # Latest package versions test
        -
            php: 7.2
            before_install:
                - composer config minimum-stability dev

        # Publishing to mini repos
        -
            stage: publish
            install: skip
            before_script:
                - echo -e "machine github.com\n  login $GITHUB_API_TOKEN" >> ~/.netrc
            script:
                - ./bin/publish
