services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ruwork\RuworkBundle\Asset\VersionStrategy\FilemtimeStrategy: ~

    Ruwork\RuworkBundle\Doctrine\NamingStrategy\RuworkNamingStrategy: ~

    Ruwork\RuworkBundle\EventListener\RedirectControllerListener:
        $conditionLanguage: "@sensio_framework_extra.security.expression_language"

    Ruwork\RuworkBundle\ExpressionLanguage\UrlExpressionLanguage: ~

    Ruwork\RuworkBundle\Mailer\Mailer:
        $swift: "@mailer"

    Ruwork\RuworkBundle\Serializer\Encoder\ExcelCsvEncoder:
        $csvEncoder: "@serializer.encoder.csv"

    Ruwork\RuworkBundle\Validator\Constraints\AliasValidator: ~
